-- This file is kept as a historical pointer only.
--
-- The schema is now maintained as numbered SQL migrations under
--   database/migrations/
--
-- On every Flask boot, database/__init__.py::init_db() runs the migration
-- runner, which applies any files not yet recorded in the schema_migrations
-- table. Run migrations manually with:
--
--   .venv/bin/python -m scripts.migrate           # apply pending
--   .venv/bin/python -m scripts.migrate --dry-run # see what would run
--   .venv/bin/python -m scripts.migrate --backup  # snapshot DB first
--
-- To add a new schema change, drop a new file in database/migrations/ named
-- with the next sequence number, e.g. 0002_add_some_column.sql. See the
-- README "Schema migrations" section for the full workflow.
